# Generated by Django 4.1.7 on 2023-04-08 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CtrlChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('datatype', models.CharField(choices=[('DECIMAL', '数值型'), ('MESSAGE', '文本型'), ('SWITCH', '开关型'), ('GPS', 'GPS型')], default='DECIMAL', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MetricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True)),
                ('direction', models.CharField(choices=[('UP', 'UP'), ('DOWN', 'DOWN')], default='UP', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('ctrlchannel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot_device.ctrlchannel')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('img', models.ImageField(blank=True, default='upload/none.jpg', upload_to='image')),
                ('device_type', models.CharField(blank=True, max_length=40)),
                ('is_custom_registered', models.BooleanField(default=False)),
                ('register_code', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE'), ('UNACTIVE', 'UNACTIVE'), ('ACTIVE', 'ACTIVE')], default='UNACTIVE', max_length=20)),
                ('protocal_type', models.CharField(choices=[('MQTT', 'MQTT'), ('HTTP', 'HTTP')], default='HTTP', max_length=20)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('activated', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ctrlchannel',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot_device.device'),
        ),
    ]
