# Generated by Django 4.1.7 on 2023-04-08 06:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iot_device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('datatype', models.CharField(choices=[('DECIMAL', '数值型'), ('MESSAGE', '文本型'), ('SWITCH', '开关型'), ('GPS', 'GPS型')], default='DECIMAL', max_length=200)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot_device.device')),
            ],
        ),
    ]
