# Generated by Django 4.1.7 on 2023-04-10 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iot_device', '0002_datachannel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IotSubDev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_title', models.CharField(blank=True, max_length=80)),
                ('topic', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('SUBSCRIBED', 'SUBSCRIBED'), ('UNSUBSCRIBED', 'UNSUBSCRIBED')], default='UNSUBSCRIBED', max_length=20)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='iot_device.device')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
